version: '3'
services:
  devops:
    image: ramu478/train
    ports:
      - "90:80"
    deploy:
      replicas: 3

  aws:
    image: ramu478/recharge
    ports:
      - "91:80"
    deploy:
      replicas: 3

  datascience:
    image: ramu478/dth
    ports:
      - "92:80"
    deploy:
      replicas: 3

  azure:
    image: ramu478/movie
    ports:
      - "93:80"
    deploy:
      replicas: 3
